export const inital_data = [
    {name:"LUP",type:"animal", image: "lup.png" },
    {name:"URS",type:"animal", image: "urs.png"},
    {name:"VULPE",type:"animal", image: "vulpe.png"},
    {name:"CAL",type:"animal", image: "cal.png"},
    {name:"VACĂ",type:"animal", image: "vaca.png"},
    {name:"CÂINE",type:"animal", image: "caine.png"},
    {name:"PISICĂ",type:"animal", image: "pisica.png"},
    {name:"ZEBRĂ",type:"animal", image: "zebra.png"},
    {name:"CAPRĂ",type:"animal", image: "capra.png"},
    {name:"MĂR",type:"fruct", image: "mar.png"},
    {name:"PARA",type:"fruct", image: "para.png"},
    {name:"PRUNĂ",type:"fruct", image: "pruna.png"},
    {name:"PIERSICĂ",type:"fruct", image: "piersica.png"},
    {name:"CAISĂ",type:"fruct", image: "caisa.png"},
    {name:"ANANAS",type:"fruct", image: "ananas.png"},
    {name:"PORTOCALĂ",type:"fruct", image: "portocala.png"},
    {name:"BANANĂ",type:"fruct", image: "banana.png"},
    {name:"KIWI",type:"fruct", image: "kiwi.png"},
    {name:"POMELO",type:"fruct", image: "pomelo.png"},
    {name:"CIREȘE",type:"fruct", image: "cirese.png"},
    {name:"CĂPȘUNI",type:"fruct", image: "capsuni.png"},
    {name:"ZMEURĂ",type:"fruct", image: "zmeura.png"},
    {name:"MURE",type:"fruct", image: "mure.png"},
]
