export const inital_data = [
    {name:"LUP",type:"animal", image: "lup.png" },
    {name:"URS",type:"animal", image: "urs.png"},
    {name:"VULPE",type:"animal", image: "vulpe.png"},
    {name:"CAL",type:"animal", image: "cal.png"},
    {name:"VACĂ",type:"animal", image: "vaca.png"},
    {name:"CÂINE",type:"animal", image: "caine.png"},
    {name:"PISICĂ",type:"animal", image: "pisica.png"},
    {name:"ZEBRĂ",type:"animal", image: "zebra.png"},
    {name:"CAPRĂ",type:"animal", image: "capra.png"},
    {name:"ȘARPE",type:"animal", image: "sarpe.png"},
    {name:"CROCODIL",type:"animal", image: "crocodil.png"},
    {name:"GĂINĂ",type:"animal", image: "gaina.png"},
    {name:"ȘORICEL",type:"animal", image: "soricel.png"},
    {name:"CANGUR",type:"animal", image: "cangur.png"},
    {name:"RINOCER",type:"animal", image: "rinocer.png"},
    {name:"HIPOPOTAM",type:"animal", image: "hipopotam.png"},
    {name:"PORUMBEL",type:"animal", image: "porumbel.png"},
    {name:"BUFNIȚĂ",type:"animal", image: "bufnita.png"},
    {name:"LEU",type:"animal", image: "leu.png"},
    {name:"TIGRU",type:"animal", image: "tigru.png"},
    {name:"KOALA",type:"animal", image: "koala.png"},
    {name:"PANDA",type:"animal", image: "panda.png"},
    {name:"ARICI",type:"animal", image: "arici.png"},
    {name:"CĂMILĂ",type:"animal", image: "camila.png"},
    {name:"VEVERIȚĂ",type:"animal", image: "veverita.png"},
    {name:"MISTREȚ",type:"animal", image: "mistret.png"},
    {name:"CERB",type:"animal", image: "cerb.png"},
    {name:"MAIMUȚĂ",type:"animal", image: "maimuta.png"},
    {name:"ELEFANT",type:"animal", image: "elefant.png"},
    {name:"GIRAFĂ",type:"animal", image: "girafa.png"},
    {name:"GORILĂ",type:"animal", image: "gorila.png"},
    {name:"ȚESTOASĂ",type:"animal", image: "testoasa.png"},
    {name:"BROASCĂ",type:"animal", image: "broasca.png"},
    {name:"MĂGAR",type:"animal", image: "magar.png"},
    {name:"OAIE",type:"animal", image: "oaie.png"},
    {name:"RAȚĂ",type:"animal", image: "rata.png"},
    {name:"COCOȘ",type:"animal", image: "cocos.png"},
    {name:"IEPURE",type:"animal", image: "iepure.png"},
    {name:"GHEPARD",type:"animal", image: "ghepard.png"},

    {name:"MĂR",type:"fruct", image: "mar.png"},
    {name:"PARA",type:"fruct", image: "para.png"},
    {name:"PRUNĂ",type:"fruct", image: "pruna.png"},
    {name:"PIERSICĂ",type:"fruct", image: "piersica.png"},
    {name:"CAISĂ",type:"fruct", image: "caisa.png"},
    {name:"ANANAS",type:"fruct", image: "ananas.png"},
    {name:"PORTOCALĂ",type:"fruct", image: "portocala.png"},
    {name:"BANANĂ",type:"fruct", image: "banana.png"},
    {name:"KIWI",type:"fruct", image: "kiwi.png"},
    {name:"POMELO",type:"fruct", image: "pomelo.png"},
    {name:"CIREȘE",type:"fruct", image: "cirese.png"},
    {name:"CĂPȘUNI",type:"fruct", image: "capsuni.png"},
    {name:"ZMEURĂ",type:"fruct", image: "zmeura.png"},
    {name:"MURE",type:"fruct", image: "mure.png"},

    {name:"ROSIE",type:"leguma", image: "rosie.png"},
    {name:"MORCOV",type:"leguma", image: "morcov.png"},
    {name:"ARDEI",type:"leguma", image: "ardei.png"},
    {name:"CASTRAVETE",type:"leguma", image: "castravete.png"},
    {name:"CARTOF",type:"leguma", image: "cartof.png"},
    {name:"CEAPA",type:"leguma", image: "ceapa.png"},
    {name:"USTUROI",type:"leguma", image: "usturoi.png"},

    {name:"MASINA",type:"vehicul", image: "masina.png"},
    {name:"TREN",type:"vehicul", image: "tren.png"},
    {name:"AUTOBUZ",type:"vehicul", image: "autobuz.png"},
    {name:"TIR",type:"vehicul", image: "tir.png"},
    {name:"MOTOCICLETA",type:"vehicul", image: "motocicleta.png"},
    {name:"BICICLETA",type:"vehicul", image: "bicicleta.png"},
    {name:"TROTINETA",type:"vehicul", image: "trotineta.png"},
    {name:"AVION",type:"vehicul", image: "avion.png"},

    {name:"ROSU",type:"culoare", image: "#FF5151"},
    {name:"PORTOCALIU",type:"culoare", image: "#EA9F2F"},
    {name:"ALBASTRU",type:"culoare", image: "#6C63FF"},
    {name:"VERDE",type:"culoare", image: "#2FEA63"},
    {name:"GALBEN",type:"culoare", image: "#E8E337"},
    {name:"MOV",type:"culoare", image: "#A020F0"},
    {name:"ROZ",type:"culoare", image: "#FFC0CB"},
    {name:"MARO",type:"culoare", image: "#964B00"},

    
    {name:"UNU",type:"cifra", image: "1"},
    {name:"DOI",type:"cifra", image: "2"},
    {name:"TREI",type:"cifra", image: "3"},
    {name:"PATRU",type:"cifra", image: "4"},
    {name:"CINCI",type:"cifra", image: "5"},
    {name:"SASE",type:"cifra", image: "6"},
    {name:"SAPTE",type:"cifra", image: "7"},
    {name:"OPT",type:"cifra", image: "8"},
    {name:"NOUA",type:"cifra", image: "9"},
    {name:"ZECE",type:"cifra", image: "10"},


]
